<template>
  <div class="container" @click="renderEmoji">
    <article @click="chooseSection">
      <i class="material-icons" data-id="1" :class="{ 'not-selected': section !== 1 }">emoji_emotions</i>
      <i class="material-icons" data-id="2" :class="{ 'not-selected': section !== 2 }">waving_hand</i>
      <i class="material-icons" data-id="3" :class="{ 'not-selected': section !== 3 }">face</i>
      <i class="material-icons" data-id="4" :class="{ 'not-selected': section !== 4 }">shopping_bag</i>
      <i class="material-icons" data-id="5" :class="{ 'not-selected': section !== 5 }">pets</i>
      <i class="material-icons" data-id="6" :class="{ 'not-selected': section !== 6 }">lunch_dining</i>
      <i class="material-icons" data-id="7" :class="{ 'not-selected': section !== 7 }">sports_basketball</i>
      <i class="material-icons" data-id="8" :class="{ 'not-selected': section !== 8 }">commute</i>
      <i class="material-icons" data-id="9" :class="{ 'not-selected': section !== 9 }">emoji_objects</i>
      <i class="material-icons" data-id="10" :class="{ 'not-selected': section !== 10 }">favorite</i>
      <i class="material-icons" data-id="11" :class="{ 'not-selected': section !== 11 }">flag</i>
    </article>
    <section v-if="section === 1">
      <div>😀</div>
      <div>😃</div>
      <div>😄</div>
      <div>😁</div>
      <div>😆</div>
      <div>😅</div>
      <div>😂</div>
      <div>🤣</div>
      <div>🥲</div>
      <div>😊</div>
      <div>😇</div>
      <div>🙂</div>
      <div>🙃</div>
      <div>😉</div>
      <div>😌</div>
      <div>😍</div>
      <div>🥰</div>
      <div>😘</div>
      <div>😗</div>
      <div>😙</div>
      <div>😚</div>
      <div>😋</div>
      <div>😛</div>
      <div>😝</div>
      <div>😜</div>
      <div>🤪</div>
      <div>🤨</div>
      <div>🧐</div>
      <div>🤓</div>
      <div>😎</div>
      <div>🥸</div>
      <div>🤩</div>
      <div>🥳</div>
      <div>😏</div>
      <div>😒</div>
      <div>😞</div>
      <div>😔</div>
      <div>😟</div>
      <div>😕</div>
      <div>🙁</div>
      <div>😣</div>
      <div>😖</div>
      <div>😫</div>
      <div>😩</div>
      <div>🥺</div>
      <div>😢</div>
      <div>😭</div>
      <div>😤</div>
      <div>😠</div>
      <div>😡</div>
      <div>🤬</div>
      <div>🤯</div>
      <div>😳</div>
      <div>🥵</div>
      <div>🥶</div>
      <div>😱</div>
      <div>😨</div>
      <div>😰</div>
      <div>😥</div>
      <div>😓</div>
      <div>🤗</div>
      <div>🤔</div>
      <div>🤭</div>
      <div>🤫</div>
      <div>🤥</div>
      <div>😶</div>
      <div>😐</div>
      <div>😑</div>
      <div>😬</div>
      <div>🙄</div>
      <div>😯</div>
      <div>😦</div>
      <div>😧</div>
      <div>😮</div>
      <div>😲</div>
      <div>🥱</div>
      <div>😴</div>
      <div>🤤</div>
      <div>😪</div>
      <div>😵</div>
      <div>🤐</div>
      <div>🥴</div>
      <div>🤢</div>
      <div>🤮</div>
      <div>🤧</div>
      <div>😷</div>
      <div>🤒</div>
      <div>🤕</div>
      <div>🤑</div>
      <div>🤠</div>
      <div>😈</div>
      <div>👿</div>
      <div>👹</div>
      <div>👺</div>
      <div>🤡</div>
      <div>💩</div>
      <div>👻</div>
      <div>💀</div>
      <div>☠️</div>
      <div>👽</div>
      <div>👾</div>
      <div>🤖</div>
      <div>🎃</div>
      <div>😺</div>
      <div>😸</div>
      <div>😹</div>
      <div>😻</div>
      <div>😼</div>
      <div>😽</div>
      <div>🙀</div>
      <div>😿</div>
      <div>😾</div>
    </section>
    <section v-if="section === 2">
      <div>👋</div>
      <div>🤚</div>
      <div>🖐</div>
      <div>✋</div>
      <div>🖖</div>
      <div>👌</div>
      <div>🤌</div>
      <div>🤏</div>
      <div>🤞</div>
      <div>🤟</div>
      <div>🤘</div>
      <div>🤙</div>
      <div>👈</div>
      <div>👉</div>
      <div>👆</div>
      <div>🖕</div>
      <div>👇</div>
      <div>👍</div>
      <div>👎</div>
      <div>✊</div>
      <div>👊</div>
      <div>🤛</div>
      <div>🤜</div>
      <div>👏</div>
      <div>🙌</div>
      <div>👐</div>
      <div>🤲</div>
      <div>🤝</div>
      <div>🙏</div>
      <div>💅</div>
      <div>🤳</div>
      <div>💪</div>
      <div>🦾</div>
      <div>🦵</div>
      <div>🦿</div>
      <div>🦶</div>
      <div>👣</div>
      <div>👂</div>
      <div>🦻</div>
      <div>👃</div>
      <div>🫀</div>
      <div>🫁</div>
      <div>🧠</div>
      <div>🦷</div>
      <div>🦴</div>
      <div>👀</div>
      <div>👁</div>
      <div>👅</div>
      <div>👄</div>
      <div>💋</div>
      <div>🩸</div>
    </section>
    <section v-if="section === 3">
      <div>👶</div>
      <div>👧</div>
      <div>🧒</div>
      <div>👦</div>
      <div>👩</div>
      <div>🧑</div>
      <div>👨</div>
      <div>👩‍🦱</div>
      <div>🧑‍🦱</div>
      <div>👨‍🦱</div>
      <div>👩‍🦰</div>
      <div>🧑‍🦰</div>
      <div>👨‍🦰</div>
      <div>👱‍♀️</div>
      <div>👱</div>
      <div>👱‍♂️</div>
      <div>👩‍🦳</div>
      <div>🧑‍🦳</div>
      <div>👨‍🦳</div>
      <div>👩‍🦲</div>
      <div>🧑‍🦲</div>
      <div>👨‍🦲</div>
      <div>🧔</div>
      <div>👵</div>
      <div>🧓</div>
      <div>👴</div>
      <div>👲</div>
      <div>👳‍♀️</div>
      <div>👳</div>
      <div>👳‍♂️</div>
      <div>🧕</div>
      <div>🧕</div>
      <div>👮‍♀️</div>
      <div>👮</div>
      <div>👮‍♂️</div>
      <div>👷‍♀️</div>
      <div>👷</div>
      <div>👷‍♂️</div>
      <div>💂‍♀️</div>
      <div>💂</div>
      <div>💂‍♂️</div>
      <div>🕵️‍♀️</div>
      <div>🕵️</div>
      <div>🕵️‍♂️</div>
      <div>👩‍⚕️</div>
      <div>🧑‍⚕️</div>
      <div>👨‍⚕️</div>
      <div>👩‍🌾</div>
      <div>🧑‍🌾</div>
      <div>👨‍🌾</div>
      <div>👩‍🍳</div>
      <div>🧑‍🍳</div>
      <div>👨‍🍳</div>
      <div>👩‍🎓</div>
      <div>🧑‍🎓</div>
      <div>👨‍🎓</div>
      <div>👩‍🎤</div>
      <div>🧑‍🎤</div>
      <div>👨‍🎤</div>
      <div>👩‍🏫</div>
      <div>🧑‍🏫</div>
      <div>👨‍🏫</div>
      <div>👩‍🏭</div>
      <div>🧑‍🏭</div>
      <div>👨‍🏭</div>
      <div>👩‍💻</div>
      <div>🧑‍💻</div>
      <div>👨‍💻</div>
      <div>👩‍💼</div>
      <div>🧑‍💼</div>
      <div>👨‍💼</div>
      <div>👩‍🔧</div>
      <div>🧑‍🔧</div>
      <div>👨‍🔧</div>
      <div>👩‍🔬</div>
      <div>🧑‍🔬</div>
      <div>👨‍🔬</div>
      <div>👩‍🎨</div>
      <div>🧑‍🎨</div>
      <div>👨‍🎨</div>
      <div>👩‍🚒</div>
      <div>🧑‍🚒</div>
      <div>👨‍🚒</div>
      <div>👩‍✈️</div>
      <div>🧑‍✈️</div>
      <div>👨‍✈️</div>
      <div>👩‍🚀</div>
      <div>🧑‍🚀</div>
      <div>👨‍🚀</div>
      <div>👩‍⚖️</div>
      <div>🧑‍⚖️</div>
      <div>👨‍⚖️</div>
      <div>👰‍♀️</div>
      <div>👰</div>
      <div>👰‍♂️</div>
      <div>🤵‍♀️</div>
      <div>🤵</div>
      <div>🤵‍♂️</div>
      <div>👸</div>
      <div>🤴</div>
      <div>🥷</div>
      <div>🦸‍♀️</div>
      <div>🦸</div>
      <div>🦸‍♂️</div>
      <div>🦹‍♀️</div>
      <div>🦹</div>
      <div>🦹‍♂️</div>
      <div>🤶</div>
      <div>🧑‍🎄</div>
      <div>🎅</div>
      <div>🧙‍♀️</div>
      <div>🧙</div>
      <div>🧙‍♂️</div>
      <div>🧝‍♀️</div>
      <div>🧝</div>
      <div>🧝‍♂️</div>
      <div>🧛‍♀️</div>
      <div>🧛</div>
      <div>🧛‍♂️</div>
      <div>🧟‍♀️</div>
      <div>🧟</div>
      <div>🧟‍♂️</div>
      <div>🧞‍♀️</div>
      <div>🧞</div>
      <div>🧞‍♂️</div>
      <div>🧜‍♀️</div>
      <div>🧜</div>
      <div>🧜‍♂️</div>
      <div>🧚‍♀️</div>
      <div>🧚</div>
      <div>🧚‍♂️</div>
      <div>👼</div>
      <div>🤰</div>
      <div>🤱</div>
      <div>👩‍🍼</div>
      <div>🧑‍🍼</div>
      <div>👨‍🍼</div>
      <div>🙇‍♀️</div>
      <div>🙇</div>
      <div>🙇‍♂️</div>
      <div>💁‍♀️</div>
      <div>💁</div>
      <div>💁‍♂️</div>
      <div>🙅‍♀️</div>
      <div>🙅</div>
      <div>🙅‍♂️</div>
      <div>🙆‍♀️</div>
      <div>🙆</div>
      <div>🙆‍♂️</div>
      <div>🙋‍♀️</div>
      <div>🙋</div>
      <div>🙋‍♂️</div>
      <div>🧏‍♀️</div>
      <div>🧏</div>
      <div>🧏‍♂️</div>
      <div>🤦‍♀️</div>
      <div>🤦</div>
      <div>🤦‍♂️</div>
      <div>🤷‍♀️</div>
      <div>🤷</div>
      <div>🤷‍♂️</div>
      <div>🙎‍♀️</div>
      <div>🙎</div>
      <div>🙎‍♂️</div>
      <div>🙍‍♀️</div>
      <div>🙍</div>
      <div>🙍‍♂️</div>
      <div>💇‍♀️</div>
      <div>💇</div>
      <div>💇‍♂️</div>
      <div>💆‍♀️</div>
      <div>💆</div>
      <div>💆‍♂️</div>
      <div>🧖‍♀️</div>
      <div>🧖</div>
      <div>🧖‍♂️</div>
      <div>💅</div>
      <div>🤳</div>
      <div>💃</div>
      <div>🕺</div>
      <div>👯‍♀️</div>
      <div>👯</div>
      <div>👯‍♂️</div>
      <div>🕴</div>
      <div>👩‍🦽</div>
      <div>🧑‍🦽</div>
      <div>👨‍🦽</div>
      <div>👩‍🦼</div>
      <div>🧑‍🦼</div>
      <div>👨‍🦼</div>
      <div>🚶‍♀️</div>
      <div>🚶</div>
      <div>🚶‍♂️</div>
      <div>👩‍🦯</div>
      <div>🧑‍🦯</div>
      <div>👨‍🦯</div>
      <div>🧎‍♀️</div>
      <div>🧎</div>
      <div>🧎‍♂️</div>
      <div>🏃‍♀️</div>
      <div>🏃</div>
      <div>🏃‍♂️</div>
      <div>🧍‍♀️</div>
      <div>🧍</div>
      <div>🧍‍♂️</div>
      <div>👭</div>
      <div>🧑‍🤝‍🧑</div>
      <div>👬</div>
      <div>👫</div>
      <div>👩‍❤️‍👩</div>
      <div>💑</div>
      <div>👨‍❤️‍👨</div>
      <div>👩‍❤️‍👨</div>
      <div>👩‍❤️‍💋‍👩</div>
      <div>💏</div>
      <div>👨‍❤️‍💋‍👨</div>
      <div>👩‍❤️‍💋‍👨</div>
      <div>👪</div>
      <div>👨‍👩‍👦</div>
      <div>👨‍👩‍👧</div>
      <div>👨‍👩‍👧‍👦</div>
      <div>👨‍👩‍👦‍👦</div>
      <div>👨‍👩‍👧‍👧</div>
      <div>👨‍👨‍👦</div>
      <div>👨‍👨‍👧</div>
      <div>👨‍👨‍👧‍👦</div>
      <div>👨‍👨‍👦‍👦</div>
      <div>👨‍👨‍👧‍👧</div>
      <div>👩‍👩‍👦</div>
      <div>👩‍👩‍👧</div>
      <div>👩‍👩‍👧‍👦</div>
      <div>👩‍👩‍👦‍👦</div>
      <div>👩‍👩‍👧‍👧</div>
      <div>👨‍👦</div>
      <div>👨‍👦‍👦</div>
      <div>👨‍👧</div>
      <div>👨‍👧‍👦</div>
      <div>👨‍👧‍👧</div>
      <div>👩‍👦</div>
      <div>👩‍👦‍👦</div>
      <div>👩‍👧</div>
      <div>👩‍👧‍👦</div>
      <div>👩‍👧‍👧</div>
      <div>🗣</div>
      <div>👤</div>
      <div>👥</div>
      <div>🫂</div>
    </section>
    <section v-if="section === 4">
      <div>🧳</div>
      <div>🌂</div>
      <div>☂️</div>
      <div>🧵</div>
      <div>🪡</div>
      <div>🪢</div>
      <div>🧶</div>
      <div>👓</div>
      <div>🕶</div>
      <div>🥽</div>
      <div>🥼</div>
      <div>🦺</div>
      <div>👔</div>
      <div>👕</div>
      <div>👖</div>
      <div>🧣</div>
      <div>🧤</div>
      <div>🧥</div>
      <div>🧦</div>
      <div>👗</div>
      <div>👘</div>
      <div>🥻</div>
      <div>🩴</div>
      <div>🩱</div>
      <div>🩲</div>
      <div>🩳</div>
      <div>👙</div>
      <div>👚</div>
      <div>👛</div>
      <div>👜</div>
      <div>👝</div>
      <div>🎒</div>
      <div>👞</div>
      <div>👟</div>
      <div>🥾</div>
      <div>🥿</div>
      <div>👠</div>
      <div>👡</div>
      <div>🩰</div>
      <div>👢</div>
      <div>👑</div>
      <div>👒</div>
      <div>🎩</div>
      <div>🎓</div>
      <div>🧢</div>
      <div>⛑</div>
      <div>🪖</div>
      <div>💄</div>
      <div>💍</div>
      <div>💼</div>
    </section>
    <section v-if="section === 5">
      <div>🐶</div>
      <div>🐱</div>
      <div>🐭</div>
      <div>🐹</div>
      <div>🐰</div>
      <div>🦊</div>
      <div>🐻</div>
      <div>🐼</div>
      <div>🐻‍❄️</div>
      <div>🐨</div>
      <div>🐯</div>
      <div>🦁</div>
      <div>🐮</div>
      <div>🐷</div>
      <div>🐽</div>
      <div>🐸</div>
      <div>🐵</div>
      <div>🙈</div>
      <div>🙉</div>
      <div>🙊</div>
      <div>🐒</div>
      <div>🐔</div>
      <div>🐧</div>
      <div>🐦</div>
      <div>🐤</div>
      <div>🐣</div>
      <div>🐥</div>
      <div>🦆</div>
      <div>🦅</div>
      <div>🦉</div>
      <div>🦇</div>
      <div>🐺</div>
      <div>🐗</div>
      <div>🐴</div>
      <div>🦄</div>
      <div>🐝</div>
      <div>🪱</div>
      <div>🐛</div>
      <div>🦋</div>
      <div>🐌</div>
      <div>🐞</div>
      <div>🐜</div>
      <div>🪰</div>
      <div>🪲</div>
      <div>🪳</div>
      <div>🦟</div>
      <div>🦗</div>
      <div>🕷</div>
      <div>🕸</div>
      <div>🦂</div>
      <div>🐢</div>
      <div>🐍</div>
      <div>🦎</div>
      <div>🦖</div>
      <div>🦕</div>
      <div>🐙</div>
      <div>🦑</div>
      <div>🦐</div>
      <div>🦞</div>
      <div>🦀</div>
      <div>🐡</div>
      <div>🐠</div>
      <div>🐟</div>
      <div>🐬</div>
      <div>🐳</div>
      <div>🐋</div>
      <div>🦈</div>
      <div>🐊</div>
      <div>🐅</div>
      <div>🐆</div>
      <div>🦓</div>
      <div>🦍</div>
      <div>🦧</div>
      <div>🦣</div>
      <div>🐘</div>
      <div>🦛</div>
      <div>🦏</div>
      <div>🐪</div>
      <div>🐫</div>
      <div>🦒</div>
      <div>🦘</div>
      <div>🦬</div>
      <div>🐃</div>
      <div>🐂</div>
      <div>🐄</div>
      <div>🐎</div>
      <div>🐖</div>
      <div>🐏</div>
      <div>🐑</div>
      <div>🦙</div>
      <div>🐐</div>
      <div>🦌</div>
      <div>🐕</div>
      <div>🐩</div>
      <div>🦮</div>
      <div>🐕‍🦺</div>
      <div>🐈</div>
      <div>🐈‍⬛</div>
      <div>🪶</div>
      <div>🐓</div>
      <div>🦃</div>
      <div>🦤</div>
      <div>🦚</div>
      <div>🦜</div>
      <div>🦢</div>
      <div>🦩</div>
      <div>🕊</div>
      <div>🐇</div>
      <div>🦝</div>
      <div>🦨</div>
      <div>🦡</div>
      <div>🦫</div>
      <div>🦦</div>
      <div>🦥</div>
      <div>🐁</div>
      <div>🐀</div>
      <div>🐿</div>
      <div>🦔</div>
      <div>🐾</div>
      <div>🐉</div>
      <div>🐲</div>
      <div>🌵</div>
      <div>🎄</div>
      <div>🌲</div>
      <div>🌳</div>
      <div>🌴</div>
      <div>🪵</div>
      <div>🌱</div>
      <div>🌿</div>
      <div>☘️</div>
      <div>🍀</div>
      <div>🎍</div>
      <div>🪴</div>
      <div>🎋</div>
      <div>🍃</div>
      <div>🍂</div>
      <div>🍁</div>
      <div>🍄</div>
      <div>🐚</div>
      <div>🪨</div>
      <div>🌾</div>
      <div>💐</div>
      <div>🌷</div>
      <div>🌹</div>
      <div>🥀</div>
      <div>🌺</div>
      <div>🌸</div>
      <div>🌼</div>
      <div>🌻</div>
      <div>🌞</div>
      <div>🌝</div>
      <div>🌛</div>
      <div>🌜</div>
      <div>🌚</div>
      <div>🌕</div>
      <div>🌖</div>
      <div>🌗</div>
      <div>🌘</div>
      <div>🌑</div>
      <div>🌒</div>
      <div>🌓</div>
      <div>🌔</div>
      <div>🌙</div>
      <div>🌎</div>
      <div>🌍</div>
      <div>🌏</div>
      <div>🪐</div>
      <div>💫</div>
      <div>⭐️</div>
      <div>🌟</div>
      <div>✨</div>
      <div>⚡️</div>
      <div>☄️</div>
      <div>💥</div>
      <div>🔥</div>
      <div>🌪</div>
      <div>🌈</div>
      <div>☀️</div>
      <div>🌤</div>
      <div>⛅️</div>
      <div>🌥</div>
      <div>☁️</div>
      <div>🌦</div>
      <div>🌧</div>
      <div>⛈</div>
      <div>🌩</div>
      <div>🌨</div>
      <div>❄️</div>
      <div>☃️</div>
      <div>⛄️</div>
      <div>🌬</div>
      <div>💨</div>
      <div>💧</div>
      <div>💦</div>
      <div>☔️</div>
      <div>☂️</div>
      <div>🌊</div>
      <div>🌫</div>
    </section>
    <section v-if="section === 6">
      <div>🍏</div>
      <div>🍎</div>
      <div>🍐</div>
      <div>🍊</div>
      <div>🍋</div>
      <div>🍌</div>
      <div>🍉</div>
      <div>🍇</div>
      <div>🍓</div>
      <div>🫐</div>
      <div>🍈</div>
      <div>🍒</div>
      <div>🍑</div>
      <div>🥭</div>
      <div>🍍</div>
      <div>🥥</div>
      <div>🥝</div>
      <div>🍅</div>
      <div>🍆</div>
      <div>🥑</div>
      <div>🥦</div>
      <div>🥬</div>
      <div>🥒</div>
      <div>🌶</div>
      <div>🫑</div>
      <div>🌽</div>
      <div>🥕</div>
      <div>🫒</div>
      <div>🧄</div>
      <div>🧅</div>
      <div>🥔</div>
      <div>🍠</div>
      <div>🥐</div>
      <div>🥯</div>
      <div>🍞</div>
      <div>🥖</div>
      <div>🥨</div>
      <div>🧀</div>
      <div>🥚</div>
      <div>🍳</div>
      <div>🧈</div>
      <div>🥞</div>
      <div>🧇</div>
      <div>🥓</div>
      <div>🥩</div>
      <div>🍗</div>
      <div>🍖</div>
      <div>🦴</div>
      <div>🌭</div>
      <div>🍔</div>
      <div>🍟</div>
      <div>🍕</div>
      <div>🫓</div>
      <div>🥪</div>
      <div>🥙</div>
      <div>🧆</div>
      <div>🌮</div>
      <div>🌯</div>
      <div>🫔</div>
      <div>🥗</div>
      <div>🥘</div>
      <div>🫕</div>
      <div>🥫</div>
      <div>🍝</div>
      <div>🍜</div>
      <div>🍲</div>
      <div>🍛</div>
      <div>🍣</div>
      <div>🍱</div>
      <div>🥟</div>
      <div>🦪</div>
      <div>🍤</div>
      <div>🍙</div>
      <div>🍚</div>
      <div>🍘</div>
      <div>🍥</div>
      <div>🥠</div>
      <div>🥮</div>
      <div>🍢</div>
      <div>🍡</div>
      <div>🍧</div>
      <div>🍨</div>
      <div>🍦</div>
      <div>🥧</div>
      <div>🧁</div>
      <div>🍰</div>
      <div>🎂</div>
      <div>🍮</div>
      <div>🍭</div>
      <div>🍬</div>
      <div>🍫</div>
      <div>🍿</div>
      <div>🍩</div>
      <div>🍪</div>
      <div>🌰</div>
      <div>🥜</div>
      <div>🍯</div>
      <div>🥛</div>
      <div>🍼</div>
      <div>🫖</div>
      <div>☕️</div>
      <div>🍵</div>
      <div>🧃</div>
      <div>🥤</div>
      <div>🧋</div>
      <div>🍶</div>
      <div>🍺</div>
      <div>🍻</div>
      <div>🥂</div>
      <div>🍷</div>
      <div>🥃</div>
      <div>🍸</div>
      <div>🍹</div>
      <div>🧉</div>
      <div>🍾</div>
      <div>🧊</div>
      <div>🥄</div>
      <div>🍴</div>
      <div>🍽</div>
      <div>🥣</div>
      <div>🥡</div>
      <div>🥢</div>
      <div>🧂</div>
    </section>
    <section v-if="section === 7">
      <div>⚽️</div>
      <div>🏀</div>
      <div>🏈</div>
      <div>⚾️</div>
      <div>🥎</div>
      <div>🎾</div>
      <div>🏐</div>
      <div>🏉</div>
      <div>🥏</div>
      <div>🎱</div>
      <div>🪀</div>
      <div>🏓</div>
      <div>🏸</div>
      <div>🏒</div>
      <div>🏑</div>
      <div>🥍</div>
      <div>🏏</div>
      <div>🪃</div>
      <div>🥅</div>
      <div>⛳️</div>
      <div>🪁</div>
      <div>🏹</div>
      <div>🎣</div>
      <div>🤿</div>
      <div>🥊</div>
      <div>🥋</div>
      <div>🎽</div>
      <div>🛹</div>
      <div>🛼</div>
      <div>🛷</div>
      <div>⛸</div>
      <div>🥌</div>
      <div>🎿</div>
      <div>⛷</div>
      <div>🏂</div>
      <div>🪂</div>
      <div>🏋️‍♀️</div>
      <div>🏋️</div>
      <div>🏋️‍♂️</div>
      <div>🤼‍♀️</div>
      <div>🤼</div>
      <div>🤼‍♂️</div>
      <div>🤸‍♀️</div>
      <div>🤸</div>
      <div>🤸‍♂️</div>
      <div>⛹️‍♀️</div>
      <div>⛹️</div>
      <div>⛹️‍♂️</div>
      <div>🤺</div>
      <div>🤾‍♀️</div>
      <div>🤾</div>
      <div>🤾‍♂️</div>
      <div>🏌️‍♀️</div>
      <div>🏌️</div>
      <div>🏌️‍♂️</div>
      <div>🏇</div>
      <div>🧘‍♀️</div>
      <div>🧘</div>
      <div>🧘‍♂️</div>
      <div>🏄‍♀️</div>
      <div>🏄</div>
      <div>🏄‍♂️</div>
      <div>🏊‍♀️</div>
      <div>🏊</div>
      <div>🏊‍♂️</div>
      <div>🤽‍♀️</div>
      <div>🤽</div>
      <div>🤽‍♂️</div>
      <div>🚣‍♀️</div>
      <div>🚣</div>
      <div>🚣‍♂️</div>
      <div>🧗‍♀️</div>
      <div>🧗</div>
      <div>🧗‍♂️</div>
      <div>🚵‍♀️</div>
      <div>🚵</div>
      <div>🚵‍♂️</div>
      <div>🚴‍♀️</div>
      <div>🚴</div>
      <div>🚴‍♂️</div>
      <div>🏆</div>
      <div>🥇</div>
      <div>🥈</div>
      <div>🥉</div>
      <div>🏅</div>
      <div>🎖</div>
      <div>🏵</div>
      <div>🎗</div>
      <div>🎫</div>
      <div>🎟</div>
      <div>🎪</div>
      <div>🤹</div>
      <div>🤹‍♂️</div>
      <div>🤹‍♀️</div>
      <div>🎭</div>
      <div>🩰</div>
      <div>🎨</div>
      <div>🎬</div>
      <div>🎤</div>
      <div>🎧</div>
      <div>🎼</div>
      <div>🎹</div>
      <div>🥁</div>
      <div>🪘</div>
      <div>🎷</div>
      <div>🎺</div>
      <div>🪗</div>
      <div>🎸</div>
      <div>🪕</div>
      <div>🎻</div>
      <div>🎲</div>
      <div>♟</div>
      <div>🎯</div>
      <div>🎳</div>
      <div>🎮</div>
      <div>🎰</div>
      <div>🧩</div>
    </section>
    <section v-if="section === 8">
      <div>🚗</div>
      <div>🚕</div>
      <div>🚙</div>
      <div>🚌</div>
      <div>🚎</div>
      <div>🏎</div>
      <div>🚓</div>
      <div>🚑</div>
      <div>🚒</div>
      <div>🚐</div>
      <div>🛻</div>
      <div>🚚</div>
      <div>🚛</div>
      <div>🚜</div>
      <div>🦯</div>
      <div>🦽</div>
      <div>🦼</div>
      <div>🛴</div>
      <div>🚲</div>
      <div>🛵</div>
      <div>🏍</div>
      <div>🛺</div>
      <div>🚨</div>
      <div>🚔</div>
      <div>🚍</div>
      <div>🚘</div>
      <div>🚖</div>
      <div>🚡</div>
      <div>🚠</div>
      <div>🚟</div>
      <div>🚃</div>
      <div>🚋</div>
      <div>🚞</div>
      <div>🚝</div>
      <div>🚄</div>
      <div>🚅</div>
      <div>🚈</div>
      <div>🚂</div>
      <div>🚆</div>
      <div>🚇</div>
      <div>🚊</div>
      <div>🚉</div>
      <div>✈️</div>
      <div>🛫</div>
      <div>🛬</div>
      <div>🛩</div>
      <div>💺</div>
      <div>🛰</div>
      <div>🚀</div>
      <div>🛸</div>
      <div>🚁</div>
      <div>🛶</div>
      <div>⛵️</div>
      <div>🚤</div>
      <div>🛥</div>
      <div>🛳</div>
      <div>⛴</div>
      <div>🚢</div>
      <div>⚓️</div>
      <div>🪝</div>
      <div>⛽️</div>
      <div>🚧</div>
      <div>🚦</div>
      <div>🚥</div>
      <div>🚏</div>
      <div>🗺</div>
      <div>🗿</div>
      <div>🗽</div>
      <div>🗼</div>
      <div>🏰</div>
      <div>🏯</div>
      <div>🏟</div>
      <div>🎡</div>
      <div>🎢</div>
      <div>🎠</div>
      <div>⛲️</div>
      <div>⛱</div>
      <div>🏖</div>
      <div>🏝</div>
      <div>🏜</div>
      <div>🌋</div>
      <div>⛰</div>
      <div>🏔</div>
      <div>🗻</div>
      <div>🏕</div>
      <div>⛺️</div>
      <div>🛖</div>
      <div>🏠</div>
      <div>🏡</div>
      <div>🏘</div>
      <div>🏚</div>
      <div>🏗</div>
      <div>🏭</div>
      <div>🏢</div>
      <div>🏬</div>
      <div>🏣</div>
      <div>🏤</div>
      <div>🏥</div>
      <div>🏦</div>
      <div>🏨</div>
      <div>🏪</div>
      <div>🏫</div>
      <div>🏩</div>
      <div>💒</div>
      <div>🏛</div>
      <div>⛪️</div>
      <div>🕌</div>
      <div>🕍</div>
      <div>🛕</div>
      <div>🕋</div>
      <div>⛩</div>
      <div>🛤</div>
      <div>🛣</div>
      <div>🗾</div>
      <div>🎑</div>
      <div>🏞</div>
      <div>🌅</div>
      <div>🌄</div>
      <div>🌠</div>
      <div>🎇</div>
      <div>🎆</div>
      <div>🌇</div>
      <div>🌆</div>
      <div>🏙</div>
      <div>🌃</div>
      <div>🌌</div>
      <div>🌉</div>
      <div>🌁</div>
    </section>
    <section v-if="section === 9">
      <div>⌚️</div>
      <div>📱</div>
      <div>📲</div>
      <div>💻</div>
      <div>⌨️</div>
      <div>🖥</div>
      <div>🖨</div>
      <div>🖱</div>
      <div>🖲</div>
      <div>🕹</div>
      <div>🗜</div>
      <div>💽</div>
      <div>💾</div>
      <div>💿</div>
      <div>📀</div>
      <div>📼</div>
      <div>📷</div>
      <div>📸</div>
      <div>📹</div>
      <div>🎥</div>
      <div>📽</div>
      <div>🎞</div>
      <div>📞</div>
      <div>☎️</div>
      <div>📟</div>
      <div>📠</div>
      <div>📺</div>
      <div>📻</div>
      <div>🎙</div>
      <div>🎚</div>
      <div>🎛</div>
      <div>🧭</div>
      <div>⏱</div>
      <div>⏲</div>
      <div>⏰</div>
      <div>🕰</div>
      <div>⌛️</div>
      <div>⏳</div>
      <div>📡</div>
      <div>🔋</div>
      <div>🔌</div>
      <div>💡</div>
      <div>🔦</div>
      <div>🕯</div>
      <div>🪔</div>
      <div>🧯</div>
      <div>🛢</div>
      <div>💸</div>
      <div>💵</div>
      <div>💴</div>
      <div>💶</div>
      <div>💷</div>
      <div>🪙</div>
      <div>💰</div>
      <div>💳</div>
      <div>💎</div>
      <div>⚖️</div>
      <div>🪜</div>
      <div>🧰</div>
      <div>🪛</div>
      <div>🔧</div>
      <div>🔨</div>
      <div>⚒</div>
      <div>🛠</div>
      <div>⛏</div>
      <div>🪚</div>
      <div>🔩</div>
      <div>⚙️</div>
      <div>🪤</div>
      <div>🧱</div>
      <div>⛓</div>
      <div>🧲</div>
      <div>🔫</div>
      <div>💣</div>
      <div>🧨</div>
      <div>🪓</div>
      <div>🔪</div>
      <div>🗡</div>
      <div>⚔️</div>
      <div>🛡</div>
      <div>🚬</div>
      <div>⚰️</div>
      <div>🪦</div>
      <div>⚱️</div>
      <div>🏺</div>
      <div>🔮</div>
      <div>📿</div>
      <div>🧿</div>
      <div>💈</div>
      <div>⚗️</div>
      <div>🔭</div>
      <div>🔬</div>
      <div>🕳</div>
      <div>🩹</div>
      <div>🩺</div>
      <div>💊</div>
      <div>💉</div>
      <div>🩸</div>
      <div>🧬</div>
      <div>🦠</div>
      <div>🧫</div>
      <div>🧪</div>
      <div>🌡</div>
      <div>🧹</div>
      <div>🪠</div>
      <div>🧺</div>
      <div>🧻</div>
      <div>🚽</div>
      <div>🚰</div>
      <div>🚿</div>
      <div>🛁</div>
      <div>🛀</div>
      <div>🧼</div>
      <div>🪥</div>
      <div>🪒</div>
      <div>🧽</div>
      <div>🪣</div>
      <div>🧴</div>
      <div>🛎</div>
      <div>🔑</div>
      <div>🗝</div>
      <div>🚪</div>
      <div>🪑</div>
      <div>🛋</div>
      <div>🛏</div>
      <div>🛌</div>
      <div>🧸</div>
      <div>🪆</div>
      <div>🖼</div>
      <div>🪞</div>
      <div>🪟</div>
      <div>🛍</div>
      <div>🛒</div>
      <div>🎁</div>
      <div>🎈</div>
      <div>🎏</div>
      <div>🎀</div>
      <div>🪄</div>
      <div>🪅</div>
      <div>🎊</div>
      <div>🎉</div>
      <div>🎎</div>
      <div>🏮</div>
      <div>🎐</div>
      <div>🧧</div>
      <div>✉️</div>
      <div>📩</div>
      <div>📨</div>
      <div>📧</div>
      <div>💌</div>
      <div>📥</div>
      <div>📤</div>
      <div>📦</div>
      <div>🏷</div>
      <div>🪧</div>
      <div>📪</div>
      <div>📫</div>
      <div>📬</div>
      <div>📭</div>
      <div>📮</div>
      <div>📯</div>
      <div>📜</div>
      <div>📃</div>
      <div>📄</div>
      <div>📑</div>
      <div>🧾</div>
      <div>📊</div>
      <div>📈</div>
      <div>📉</div>
      <div>🗒</div>
      <div>🗓</div>
      <div>📆</div>
      <div>📅</div>
      <div>🗑</div>
      <div>📇</div>
      <div>🗃</div>
      <div>🗳</div>
      <div>🗄</div>
      <div>📋</div>
      <div>📁</div>
      <div>📂</div>
      <div>🗂</div>
      <div>🗞</div>
      <div>📰</div>
      <div>📓</div>
      <div>📔</div>
      <div>📒</div>
      <div>📕</div>
      <div>📗</div>
      <div>📘</div>
      <div>📙</div>
      <div>📚</div>
      <div>📖</div>
      <div>🔖</div>
      <div>🧷</div>
      <div>🔗</div>
      <div>📎</div>
      <div>🖇</div>
      <div>📐</div>
      <div>📏</div>
      <div>🧮</div>
      <div>📌</div>
      <div>📍</div>
      <div>✂️</div>
      <div>🖊</div>
      <div>🖋</div>
      <div>✒️</div>
      <div>🖌</div>
      <div>🖍</div>
      <div>📝</div>
      <div>✏️</div>
      <div>🔍</div>
      <div>🔎</div>
      <div>🔏</div>
      <div>🔐</div>
      <div>🔒</div>
      <div>🔓</div>
    </section>
    <section v-if="section === 10">
      <div>❤️</div>
      <div>🧡</div>
      <div>💛</div>
      <div>💚</div>
      <div>💙</div>
      <div>💜</div>
      <div>🖤</div>
      <div>🤍</div>
      <div>🤎</div>
      <div>💔</div>
      <div>❣️</div>
      <div>💕</div>
      <div>💞</div>
      <div>💓</div>
      <div>💗</div>
      <div>💖</div>
      <div>💘</div>
      <div>💝</div>
      <div>💟</div>
      <div>☮️</div>
      <div>✝️</div>
      <div>☪️</div>
      <div>🕉</div>
      <div>☸️</div>
      <div>✡️</div>
      <div>🔯</div>
      <div>🕎</div>
      <div>☯️</div>
      <div>☦️</div>
      <div>🛐</div>
      <div>⛎</div>
      <div>♈️</div>
      <div>♉️</div>
      <div>♊️</div>
      <div>♋️</div>
      <div>♌️</div>
      <div>♍️</div>
      <div>♎️</div>
      <div>♏️</div>
      <div>♐️</div>
      <div>♑️</div>
      <div>♒️</div>
      <div>♓️</div>
      <div>🆔</div>
      <div>⚛️</div>
      <div>🉑</div>
      <div>☢️</div>
      <div>☣️</div>
      <div>📴</div>
      <div>📳</div>
      <div>🈶</div>
      <div>🈚️</div>
      <div>🈸</div>
      <div>🈺</div>
      <div>🈷️</div>
      <div>✴️</div>
      <div>🆚</div>
      <div>💮</div>
      <div>🉐</div>
      <div>㊙️</div>
      <div>㊗️</div>
      <div>🈴</div>
      <div>🈵</div>
      <div>🈹</div>
      <div>🈲</div>
      <div>🅰️</div>
      <div>🅱️</div>
      <div>🆎</div>
      <div>🆑</div>
      <div>🅾️</div>
      <div>🆘</div>
      <div>❌</div>
      <div>⭕️</div>
      <div>🛑</div>
      <div>⛔️</div>
      <div>📛</div>
      <div>🚫</div>
      <div>💯</div>
      <div>💢</div>
      <div>♨️</div>
      <div>🚷</div>
      <div>🚯</div>
      <div>🚳</div>
      <div>🚱</div>
      <div>🔞</div>
      <div>📵</div>
      <div>🚭</div>
      <div>❗️</div>
      <div>❕</div>
      <div>❓</div>
      <div>❔</div>
      <div>‼️</div>
      <div>⁉️</div>
      <div>🔅</div>
      <div>🔆</div>
      <div>〽️</div>
      <div>⚠️</div>
      <div>🚸</div>
      <div>🔱</div>
      <div>⚜️</div>
      <div>🔰</div>
      <div>♻️</div>
      <div>✅</div>
      <div>🈯️</div>
      <div>💹</div>
      <div>❇️</div>
      <div>✳️</div>
      <div>❎</div>
      <div>🌐</div>
      <div>💠</div>
      <div>Ⓜ️</div>
      <div>🌀</div>
      <div>💤</div>
      <div>🏧</div>
      <div>🚾</div>
      <div>♿️</div>
      <div>🅿️</div>
      <div>🛗</div>
      <div>🈳</div>
      <div>🈂️</div>
      <div>🛂</div>
      <div>🛃</div>
      <div>🛄</div>
      <div>🛅</div>
      <div>🚹</div>
      <div>🚺</div>
      <div>🚼</div>
      <div>⚧</div>
      <div>🚻</div>
      <div>🚮</div>
      <div>🎦</div>
      <div>📶</div>
      <div>🈁</div>
      <div>🔣</div>
      <div>ℹ️</div>
      <div>🔤</div>
      <div>🔡</div>
      <div>🔠</div>
      <div>🆖</div>
      <div>🆗</div>
      <div>🆙</div>
      <div>🆒</div>
      <div>🆕</div>
      <div>🆓</div>
      <div>0️⃣</div>
      <div>1️⃣</div>
      <div>2️⃣</div>
      <div>3️⃣</div>
      <div>4️⃣</div>
      <div>5️⃣</div>
      <div>6️⃣</div>
      <div>7️⃣</div>
      <div>8️⃣</div>
      <div>9️⃣</div>
      <div>🔟</div>
      <div>🔢</div>
      <div>#️⃣</div>
      <div>*️⃣</div>
      <div>⏏️</div>
      <div>▶️</div>
      <div>⏸</div>
      <div>⏯</div>
      <div>⏹</div>
      <div>⏺</div>
      <div>⏭</div>
      <div>⏮</div>
      <div>⏩</div>
      <div>⏪</div>
      <div>⏫</div>
      <div>⏬</div>
      <div>◀️</div>
      <div>🔼</div>
      <div>🔽</div>
      <div>➡️</div>
      <div>⬅️</div>
      <div>⬆️</div>
      <div>⬇️</div>
      <div>↗️</div>
      <div>↘️</div>
      <div>↙️</div>
      <div>↖️</div>
      <div>↕️</div>
      <div>↔️</div>
      <div>↪️</div>
      <div>↩️</div>
      <div>⤴️</div>
      <div>⤵️</div>
      <div>🔀</div>
      <div>🔁</div>
      <div>🔂</div>
      <div>🔄</div>
      <div>🔃</div>
      <div>🎵</div>
      <div>🎶</div>
      <div>➕</div>
      <div>➖</div>
      <div>➗</div>
      <div>✖️</div>
      <div>♾</div>
      <div>💲</div>
      <div>💱</div>
      <div>™️</div>
      <div>©️</div>
      <div>®️</div>
      <div>〰️</div>
      <div>➰</div>
      <div>➿</div>
      <div>🔚</div>
      <div>🔙</div>
      <div>🔛</div>
      <div>🔝</div>
      <div>🔜</div>
      <div>✔️</div>
      <div>☑️</div>
      <div>🔘</div>
      <div>🔴</div>
      <div>🟠</div>
      <div>🟡</div>
      <div>🟢</div>
      <div>🔵</div>
      <div>🟣</div>
      <div>⚫️</div>
      <div>⚪️</div>
      <div>🟤</div>
      <div>🔺</div>
      <div>🔻</div>
      <div>🔸</div>
      <div>🔹</div>
      <div>🔶</div>
      <div>🔷</div>
      <div>🔳</div>
      <div>🔲</div>
      <div>▪️</div>
      <div>▫️</div>
      <div>◾️</div>
      <div>◽️</div>
      <div>◼️</div>
      <div>◻️</div>
      <div>🟥</div>
      <div>🟧</div>
      <div>🟨</div>
      <div>🟩</div>
      <div>🟦</div>
      <div>🟪</div>
      <div>⬛️</div>
      <div>⬜️</div>
      <div>🟫</div>
      <div>🔈</div>
      <div>🔇</div>
      <div>🔉</div>
      <div>🔊</div>
      <div>🔔</div>
      <div>🔕</div>
      <div>📣</div>
      <div>📢</div>
      <div>👁‍🗨</div>
      <div>💬</div>
      <div>💭</div>
      <div>🗯</div>
      <div>♠️</div>
      <div>♣️</div>
      <div>♥️</div>
      <div>♦️</div>
      <div>🃏</div>
      <div>🎴</div>
      <div>🀄️</div>
      <div>🕐</div>
      <div>🕑</div>
      <div>🕒</div>
      <div>🕓</div>
      <div>🕔</div>
      <div>🕕</div>
      <div>🕖</div>
      <div>🕗</div>
      <div>🕘</div>
      <div>🕙</div>
      <div>🕚</div>
      <div>🕛</div>
      <div>🕜</div>
      <div>🕝</div>
      <div>🕞</div>
      <div>🕟</div>
      <div>🕠</div>
      <div>🕡</div>
      <div>🕢</div>
      <div>🕣</div>
      <div>🕤</div>
      <div>🕥</div>
      <div>🕦</div>
      <div>🕧</div>
    </section>
    <section v-if="section === 11">
      <div>🏳️</div>
      <div>🏴</div>
      <div>🏁</div>
      <div>🚩</div>
      <div>🏳️‍🌈</div>
      <div>🏳️‍⚧️</div>
      <div>🏴‍☠️</div>
      <div>🇦🇫</div>
      <div>🇦🇽</div>
      <div>🇦🇱</div>
      <div>🇩🇿</div>
      <div>🇦🇸</div>
      <div>🇦🇩</div>
      <div>🇦🇴</div>
      <div>🇦🇮</div>
      <div>🇦🇶</div>
      <div>🇦🇬</div>
      <div>🇦🇷</div>
      <div>🇦🇲</div>
      <div>🇦🇼</div>
      <div>🇦🇺</div>
      <div>🇦🇹</div>
      <div>🇦🇿</div>
      <div>🇧🇸</div>
      <div>🇧🇭</div>
      <div>🇧🇩</div>
      <div>🇧🇧</div>
      <div>🇧🇾</div>
      <div>🇧🇪</div>
      <div>🇧🇿</div>
      <div>🇧🇯</div>
      <div>🇧🇲</div>
      <div>🇧🇹</div>
      <div>🇧🇴</div>
      <div>🇧🇦</div>
      <div>🇧🇼</div>
      <div>🇧🇷</div>
      <div>🇮🇴</div>
      <div>🇻🇬</div>
      <div>🇧🇳</div>
      <div>🇧🇬</div>
      <div>🇧🇫</div>
      <div>🇧🇮</div>
      <div>🇰🇭</div>
      <div>🇨🇲</div>
      <div>🇨🇦</div>
      <div>🇮🇨</div>
      <div>🇨🇻</div>
      <div>🇧🇶</div>
      <div>🇰🇾</div>
      <div>🇨🇫</div>
      <div>🇹🇩</div>
      <div>🇨🇱</div>
      <div>🇨🇳</div>
      <div>🇨🇽</div>
      <div>🇨🇨</div>
      <div>🇨🇴</div>
      <div>🇰🇲</div>
      <div>🇨🇬</div>
      <div>🇨🇩</div>
      <div>🇨🇰</div>
      <div>🇨🇷</div>
      <div>🇨🇮</div>
      <div>🇭🇷</div>
      <div>🇨🇺</div>
      <div>🇨🇼</div>
      <div>🇨🇾</div>
      <div>🇨🇿</div>
      <div>🇩🇰</div>
      <div>🇩🇯</div>
      <div>🇩🇲</div>
      <div>🇩🇴</div>
      <div>🇪🇨</div>
      <div>🇪🇬</div>
      <div>🇸🇻</div>
      <div>🇬🇶</div>
      <div>🇪🇷</div>
      <div>🇪🇪</div>
      <div>🇪🇹</div>
      <div>🇪🇺</div>
      <div>🇫🇰</div>
      <div>🇫🇴</div>
      <div>🇫🇯</div>
      <div>🇫🇮</div>
      <div>🇫🇷</div>
      <div>🇬🇫</div>
      <div>🇵🇫</div>
      <div>🇹🇫</div>
      <div>🇬🇦</div>
      <div>🇬🇲</div>
      <div>🇬🇪</div>
      <div>🇩🇪</div>
      <div>🇬🇭</div>
      <div>🇬🇮</div>
      <div>🇬🇷</div>
      <div>🇬🇱</div>
      <div>🇬🇩</div>
      <div>🇬🇵</div>
      <div>🇬🇺</div>
      <div>🇬🇹</div>
      <div>🇬🇬</div>
      <div>🇬🇳</div>
      <div>🇬🇼</div>
      <div>🇬🇾</div>
      <div>🇭🇹</div>
      <div>🇭🇳</div>
      <div>🇭🇰</div>
      <div>🇭🇺</div>
      <div>🇮🇸</div>
      <div>🇮🇳</div>
      <div>🇮🇩</div>
      <div>🇮🇷</div>
      <div>🇮🇶</div>
      <div>🇮🇪</div>
      <div>🇮🇲</div>
      <div>🇮🇱</div>
      <div>🇮🇹</div>
      <div>🇯🇲</div>
      <div>🇯🇵</div>
      <div>🎌</div>
      <div>🇯🇪</div>
      <div>🇯🇴</div>
      <div>🇰🇿</div>
      <div>🇰🇪</div>
      <div>🇰🇮</div>
      <div>🇽🇰</div>
      <div>🇰🇼</div>
      <div>🇰🇬</div>
      <div>🇱🇦</div>
      <div>🇱🇻</div>
      <div>🇱🇧</div>
      <div>🇱🇸</div>
      <div>🇱🇷</div>
      <div>🇱🇾</div>
      <div>🇱🇮</div>
      <div>🇱🇹</div>
      <div>🇱🇺</div>
      <div>🇲🇴</div>
      <div>🇲🇰</div>
      <div>🇲🇬</div>
      <div>🇲🇼</div>
      <div>🇲🇾</div>
      <div>🇲🇻</div>
      <div>🇲🇱</div>
      <div>🇲🇹</div>
      <div>🇲🇭</div>
      <div>🇲🇶</div>
      <div>🇲🇷</div>
      <div>🇲🇺</div>
      <div>🇾🇹</div>
      <div>🇲🇽</div>
      <div>🇫🇲</div>
      <div>🇲🇩</div>
      <div>🇲🇨</div>
      <div>🇲🇳</div>
      <div>🇲🇪</div>
      <div>🇲🇸</div>
      <div>🇲🇦</div>
      <div>🇲🇿</div>
      <div>🇲🇲</div>
      <div>🇳🇦</div>
      <div>🇳🇷</div>
      <div>🇳🇵</div>
      <div>🇳🇱</div>
      <div>🇳🇨</div>
      <div>🇳🇿</div>
      <div>🇳🇮</div>
      <div>🇳🇪</div>
      <div>🇳🇬</div>
      <div>🇳🇺</div>
      <div>🇳🇫</div>
      <div>🇰🇵</div>
      <div>🇲🇵</div>
      <div>🇳🇴</div>
      <div>🇴🇲</div>
      <div>🇵🇰</div>
      <div>🇵🇼</div>
      <div>🇵🇸</div>
      <div>🇵🇦</div>
      <div>🇵🇬</div>
      <div>🇵🇾</div>
      <div>🇵🇪</div>
      <div>🇵🇭</div>
      <div>🇵🇳</div>
      <div>🇵🇱</div>
      <div>🇵🇹</div>
      <div>🇵🇷</div>
      <div>🇶🇦</div>
      <div>🇷🇪</div>
      <div>🇷🇴</div>
      <div>🇷🇺</div>
      <div>🇷🇼</div>
      <div>🇼🇸</div>
      <div>🇸🇲</div>
      <div>🇸🇦</div>
      <div>🇸🇳</div>
      <div>🇷🇸</div>
      <div>🇸🇨</div>
      <div>🇸🇱</div>
      <div>🇸🇬</div>
      <div>🇸🇽</div>
      <div>🇸🇰</div>
      <div>🇸🇮</div>
      <div>🇬🇸</div>
      <div>🇸🇧</div>
      <div>🇸🇴</div>
      <div>🇿🇦</div>
      <div>🇰🇷</div>
      <div>🇸🇸</div>
      <div>🇪🇸</div>
      <div>🇱🇰</div>
      <div>🇧🇱</div>
      <div>🇸🇭</div>
      <div>🇰🇳</div>
      <div>🇱🇨</div>
      <div>🇵🇲</div>
      <div>🇻🇨</div>
      <div>🇸🇩</div>
      <div>🇸🇷</div>
      <div>🇸🇿</div>
      <div>🇸🇪</div>
      <div>🇨🇭</div>
      <div>🇸🇾</div>
      <div>🇹🇼</div>
      <div>🇹🇯</div>
      <div>🇹🇿</div>
      <div>🇹🇭</div>
      <div>🇹🇱</div>
      <div>🇹🇬</div>
      <div>🇹🇰</div>
      <div>🇹🇴</div>
      <div>🇹🇹</div>
      <div>🇹🇳</div>
      <div>🇹🇷</div>
      <div>🇹🇲</div>
      <div>🇹🇨</div>
      <div>🇹🇻</div>
      <div>🇻🇮</div>
      <div>🇺🇬</div>
      <div>🇺🇦</div>
      <div>🇦🇪</div>
      <div>🇬🇧</div>
      <div>🏴󠁧󠁢󠁥󠁮󠁧󠁿</div>
      <div>🏴󠁧󠁢󠁳󠁣󠁴󠁿</div>
      <div>🏴󠁧󠁢󠁷󠁬󠁳󠁿</div>
      <div>🇺🇳</div>
      <div>🇺🇸</div>
      <div>🇺🇾</div>
      <div>🇺🇿</div>
      <div>🇻🇺</div>
      <div>🇻🇦</div>
      <div>🇻🇪</div>
      <div>🇻🇳</div>
      <div>🇼🇫</div>
      <div>🇪🇭</div>
      <div>🇾🇪</div>
      <div>🇿🇲</div>
      <div>🇿🇼</div>
    </section>
  </div>
</template>

<script>
export default {
  data() {
    return {
      section: 1,
    };
  },
  methods: {
    renderEmoji(e) {
      if (e.target.nodeName === 'DIV') {
        this.$emit('emoji', e.target.innerText);
      }
    },
    chooseSection(e) {
      if (e.target.nodeName === 'I') {
        this.section = Number(e.target.getAttribute('data-id'));
      }
    },
  },
};
</script>

<style scoped>
div.container {
  background-color: #fff;
  width: min-content;
}
div.container section {
  width: 100vw;
  display: grid;
  grid-template-rows: repeat(3, min-content);
  grid-auto-flow: column;
  overflow: auto;
  padding-bottom: 0.5rem;
}
div.container article {
  background-color: #00acc1;
  border-top: 1px solid #fff;
  height: 40px;
  display: flex;
  justify-content: space-around;
  align-items: center;
}
div.container div {
  font-size: 1.5rem;
  padding: 0.2rem 0.5rem;
}
article i {
  color: #eceff1;
}
i.not-selected {
  opacity: 0.5;
}
</style>
